- name: download the ESB
  get_url: url=http://product-dist.wso2.com/products/enterprise-service-bus/5.0.0/wso2esb-5.0.0.zip dest=/root/wso2esb-5.0.0.zip headers="Referer:http://wso2.com/legacy-products"

- name: unpack the ESB
  unarchive: src=/root/wso2esb-5.0.0.zip remote_src=True dest=/opt

- name: copy files
  shell: cp -r /opt/wso2esb-5.0.0 /opt/wso2esb-{{ subrole }} creates=/opt/wso2esb-{{ subrole }}

- name: create a user
  user: name={{ wso2_esb_user }}

- name: set permissions on a components dir
  file: state=directory recurse=yes dest=/opt/wso2esb-{{ subrole }}/ owner={{ wso2_esb_user }} group={{ wso2_esb_user }}

- name: put carbon.xml
  template: src=carbon.xml dest=/opt/wso2esb-{{ subrole }}/repository/conf/carbon.xml backup=yes

- name: download the PostgreSQL driver
  get_url: url=https://jdbc.postgresql.org/download/postgresql-42.1.1.jar dest=/opt/wso2esb-{{ subrole }}/repository/components/lib/

- name: put master-datasources.xml
  template: src=master-datasources.xml dest=/opt/wso2esb-{{ subrole }}/repository/conf/datasources/master-datasources.xml backup=yes

- name: put user-mgt.xml
  template: src=user-mgt.xml dest=/opt/wso2esb-{{ subrole }}/repository/conf/user-mgt.xml backup=yes

- name: put registry.xml
  template: src=registry.xml dest=/opt/wso2esb-{{ subrole }}/repository/conf/registry.xml backup=yes

- name: put axis2.xml
  template: src=axis2.xml dest=/opt/wso2esb-{{ subrole }}/repository/conf/axis2/axis2.xml backup=yes

- name: put systemd unit file to its destination
  template: src=wso2-esb.service dest=/etc/systemd/system/wso2-esb-{{ subrole }}.service owner=root group=root mode=0644
  notify: systemctl daemon-reload

- name: enable wso2-esb service
  service: name=wso2-esb-{{ subrole }} enabled=yes state=started
